name: "Install Theos"
description: "Install Theos and prepare it for building projects"
author: "Randomblock1"
branding:
  icon: download-cloud
  color: purple

inputs:
  theos-dir:
    description: "Where to install Theos"
    required: false
    default: ${{ github.workspace }}/theos
  theos-src:
    description: "Git URL to clone Theos from"
    required: false
    default: "https://github.com/roothide/theos"
  theos-sdks:
    description: "GitHub repository URL for iOS SDKs"
    required: false
    default: "https://github.com/theos/sdks"
  theos-sdks-branch:
    description: "Branch to clone SDKs from"
    required: false
    default: "master"
  orion:
    description: "Enable Orion (Swift tweak support)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # ---------------- MacOS Setup ----------------
    - name: Setup MacOS dependencies
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install ldid make
        echo "PATH=$(brew --prefix make)/libexec/gnubin:$PATH" >> $GITHUB_ENV

    # ---------------- Linux Setup ----------------
    - name: Setup Linux dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential fakeroot libtinfo5 libz3-dev rsync curl perl unzip git libplist-utils p7zip-full

    # ---------------- Setup THEOS env ----------------
    - name: Setup THEOS environment
      shell: bash
      run: |
        echo "THEOS=${{ inputs.theos-dir }}" >> $GITHUB_ENV

    # ---------------- Download Theos ----------------
    - name: Download Theos
      shell: bash
      run: |
        if [ ! -d "${{ inputs.theos-dir }}" ]; then
          git clone --recursive ${{ inputs.theos-src }} ${{ inputs.theos-dir }}
          echo "Theos successfully downloaded."
        else
          echo "Theos already cached."
        fi

    # ---------------- Get Linux Toolchain ----------------
    - name: Get Linux toolchain
      shell: bash
      if: runner.os == 'Linux'
      run: |
        if [[ -d "${{ inputs.theos-dir }}/toolchain" && "$(ls -A ${{ inputs.theos-dir }}/toolchain)" ]]; then
          echo "Linux toolchain already cached, skipping..."
        else
          TMP_DL=$(mktemp -d)
          wget --no-verbose https://github.com/kabiroberai/swift-toolchain-linux/releases/download/v2.3.0/swift-5.8-ubuntu22.04.tar.xz -P $TMP_DL
          mkdir -p ${{ inputs.theos-dir }}/toolchain
          tar -xvf $TMP_DL/swift-5.8-ubuntu22.04.tar.xz -C ${{ inputs.theos-dir }}/toolchain
          rm -rf $TMP_DL
        fi

    # ---------------- Get SDKs ----------------
    - name: Get SDKs
      shell: bash
      run: |
        SDK_DIR="${{ inputs.theos-dir }}/sdks"
        mkdir -p "$SDK_DIR"
        if [[ "$(ls -A $SDK_DIR 2>/dev/null)" ]]; then
          echo "Theos SDKs already cached, skipping..."
        else
          cd "$SDK_DIR"
          wget --no-verbose "${{ inputs.theos-sdks }}/archive/${{ inputs.theos-sdks-branch }}.zip" -O sdk.zip
          TMP=$(mktemp -d)
          7z x sdk.zip -o"$TMP"
          mv "$TMP"/*-${{ inputs.theos-sdks-branch }}/*.sdk "$SDK_DIR"
          rm -rf sdk.zip "$TMP"
        fi

    # ---------------- Enable Orion ----------------
    - name: Enable Orion (Swift tweaks)
      shell: bash
      if: inputs.orion == 'true'
      run: |
        cd ${{ inputs.theos-dir }}
        git fetch
        git checkout orion
        git submodule update --init
