name: 'Theos Build Action'
description: 'Build iOS tweaks or apps using Theos on GitHub Actions'
author: 'axs66'
branding:
  icon: 'cpu'
  color: 'purple'

inputs:
  project-path:
    description: 'Path to your Theos project (where Makefile is located)'
    required: false
    default: '.'
  target:
    description: 'Make target to build (e.g., package, install)'
    required: false
    default: 'package'
  theos-repo:
    description: 'Theos repo URL'
    required: false
    default: 'https://github.com/theos/theos.git'
  theos-ref:
    description: 'Theos branch or tag'
    required: false
    default: 'master'
  sdk:
    description: 'iOS SDK version (used with theos/sdks)'
    required: false
    default: '14.5'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential fakeroot ldid git perl clang make unzip wget curl

    - name: Setup Theos
      shell: bash
      run: |
        echo "🔧 Setting up Theos..."
        export THEOS=$HOME/theos
        git clone --recursive --branch ${{ inputs.theos-ref }} ${{ inputs.theos-repo }} $THEOS

        # 下载 iOS SDKs（如果你没有自己的缓存，可以这样）
        mkdir -p $THEOS/sdks
        wget -q https://github.com/theos/sdks/archive/refs/heads/master.zip -O sdks.zip
        unzip -q sdks.zip -d $THEOS
        mv $THEOS/sdks-master/* $THEOS/sdks/
        rm -rf sdks.zip $THEOS/sdks-master

        echo "THEOS=$THEOS" >> $GITHUB_ENV

    - name: Build Project
      shell: bash
      working-directory: ${{ inputs.project-path }}
      run: |
        echo "📦 Building project with Theos..."
        make ${{ inputs.target }}
